Repository santosderek/Vitality, pull requests merged in 2020-10, with the labels that each got.

#16 First iteration of the configuration.py / configuration.json files
  vitality/configuration.json
  vitality/configuration.py
Labels: enhancement

#18 Wilson charles/dev
  vitality/static/login.css
  vitality/templates/createuser.html
  vitality/templates/login.html
Labels: enhancement

#19 Adding /login and /createuser
  vitality/__init__.py
  vitality/templates/createuser.html
  vitality/templates/index.html
  vitality/templates/login.html
Labels: enhancement

#20 Laruffaelijah dev
  .gitignore
  requirements.txt
  schema_atlas.py
  schema_local.py
  tests/example.py
  vitality/__init__.py
  vitality/configuration.json
  vitality/configuration.py
Labels: enhancement

#21 Removed dnspython.
  requirements.txt
Labels: enhancement

#22 Added our Vitality logo to the static files.
  vitality/static/Heart Logo.png
Labels: enhancement

#24 Update .gitignore
  .gitignore
Labels: enhancement

#25 Added /login and /createuser functionality
  vitality/__init__.py
  vitality/static/login.css
  vitality/templates/createuser.html
  vitality/templates/login.html
  vitality/templates/profile.html
  vitality/user.py
Labels: enhancement

#30 Vitality Logo
  README.md
  vitality/helper/schema_atlas.py
  vitality/helper/schema_local.py
  vitality/static/HeartLogo.png
Labels: enhancement

#31 Readded schema files to helper folder.
  helper/schema_atlas.py
  helper/schema_local.py
Labels: enhancement

#35 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#34 User settings page
  vitality/__init__.py
  vitality/templates/profile.html
  vitality/templates/usersettings.html
  vitality/user.py
Labels: enhancement

#36 Escaped user input using the Markupsafe package.
  requirements.txt
  vitality/__init__.py
Labels: enhancement

#38 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#33 Create database.py
  database.py
  tests/database_test.py
  vitality/__init__.py
Labels: enhancement

#44 Added unittest module functionality to automate the unit tests.
  tests/__init__.py
  tests/database_test.py
  tests/test_database.py
  vitality/__init__.py
  vitality/database.py
  vitality/user.py
Labels: enhancement

#46 Added the escape function surounding the user input in user settings.
  vitality/__init__.py
Labels: enhancement

#45 Moved images folder to static. Changed all img tags to use url_for.
  vitality/static/images/equipment.jpg
  vitality/static/images/lunge.jpg
  vitality/static/images/pushup.jpg
  vitality/templates/workout.html
  vitality/templates/workoutlist.html
Labels: enhancement

#47 Fixed bug where workout.html is not in the static folder.
  vitality/templates/workoutlist.html
Labels: bug, enhancement

#49 Using databse.py to login, create a user, and change user settings.
  vitality/__init__.py
  vitality/database.py
  vitality/templates/createuser.html
  vitality/templates/usersettings.html
Labels: bug, enhancement

#50 workout.py
  helper/schema_local.py
  vitality/workout.py
Labels: enhancement

#51 Fixed name within as_dict
  vitality/workout.py
Labels: bug, enhancement

#53 Added more tests to test_database.py
  tests/test_database.py
Labels: enhancement

#54 Update schema_atlas.py
  helper/schema_atlas.py
Labels: enhancement

#58 Added the configuration class to the init and test files
  configuration.json
  tests/test_database.py
  vitality/__init__.py
  vitality/configuration.py
Labels: enhancement

#59 Created add_workout method to database class, as well as created a test for add_workout
  tests/test_database.py
  vitality/database.py
  vitality/workout.py
Labels: enhancement

#61 Laruffaelijah dev
  tests/test_database.py
  vitality/database.py
  vitality/workout.py
Labels: bug

#62 Created trainer.py
  vitality/trainer.py
Labels: enhancement

#66 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#67 Added a logout button and route to log the user out
  vitality/__init__.py
  vitality/templates/profile.html
  vitality/templates/usersettings.html
Labels: enhancement

#68 Santosderek dev
  vitality/__init__.py
  vitality/templates/createuser.html
  vitality/templates/login.html
  vitality/templates/usersettings.html
Labels: enhancement

#69 Fixing Formatting
  vitality/templates/base.html
  vitality/templates/index.html
  vitality/templates/newroutine.html
  vitality/templates/profile.html
  vitality/templates/search.html
  vitality/templates/workoutlist.html
Labels: enhancement

#70 Sorting templates.
  vitality/__init__.py
  vitality/templates/account/createuser.html
  vitality/templates/account/login.html
  vitality/templates/account/profile.html
  vitality/templates/account/usersettings.html
  vitality/templates/diet/placeholder.html
  vitality/templates/trainee/placeholder.html
  vitality/templates/trainer/placeholder.html
  vitality/templates/workout_pages/newroutine.html
  vitality/templates/workout_pages/search.html
  vitality/templates/workout_pages/workout.html
  vitality/templates/workout_pages/workoutlist.html
Labels: enhancement

#71 Moving css and image files into respective folders.
  README.md
  vitality/static/css/base.css
  vitality/static/css/login.css
  vitality/static/images/heartlogo.png
  vitality/templates/account/login.html
  vitality/templates/index.html
Labels: enhancement

#75 Profile can now populate the page based on supplied username.
  vitality/__init__.py
  vitality/templates/account/profile.html
  vitality/templates/account/usersettings.html
Labels: enhancement

#74 Added routes to the trainer pages. Created the foundation of the list…
  vitality/__init__.py
  vitality/static/images/profile.svg
  vitality/templates/trainer/list_trainees.html
  vitality/templates/trainer/overview.html
  vitality/templates/trainer/placeholder.html
  vitality/templates/trainer/schedule.html
Labels: enhancement

#78 Login redirect bug fix
  vitality/__init__.py
Labels: bugfix

#80 Added test_user.py and test_trainer.py
  tests/test_trainer.py
  tests/test_user.py
Labels: enhancement

#90 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#91 Added all required doc comments to all functions.
  vitality/__init__.py
  vitality/configuration.py
  vitality/database.py
  vitality/trainer.py
  vitality/user.py
  vitality/workout.py
Labels: documentation

#92 Create python-app.yml
  .github/workflows/python-app.yml
Labels: enhancement

#93 Update trainer.py
  vitality/trainer.py
Labels: enhancement

#94 Update python-app.yml
  .github/workflows/python-app.yml
Labels: enhancement

#95 Update python-app.yml
  .github/workflows/python-app.yml
Labels: enhancement

#96 Rename python-app.yml to Unittests-and-Dependencies.yml
  .github/workflows/Unittests-and-Dependencies.yml
Labels: enhancement

#97 Update README.md
  README.md
Labels: enhancement

#77 Bug fix where if multiple usernames are found, the test_set_username function would fail.
  tests/test_database.py
Labels: bugfix

#98 Updated base.html and home.html
  vitality/__init__.py
  vitality/static/css/base.css
  vitality/static/css/bootstrap-grid.css
  vitality/static/css/bootstrap-grid.css.map
  vitality/static/css/bootstrap-grid.min.css
  vitality/static/css/bootstrap-grid.min.css.map
  vitality/static/css/bootstrap-reboot.css
  vitality/static/css/bootstrap-reboot.css.map
  vitality/static/css/bootstrap-reboot.min.css
  vitality/static/css/bootstrap-reboot.min.css.map
  vitality/static/css/bootstrap.css
  vitality/static/css/bootstrap.css.map
  vitality/static/css/bootstrap.min.css
  vitality/static/css/bootstrap.min.css.map
  vitality/static/images/heart.ico
  vitality/static/images/list.svg
  vitality/static/images/map.svg
  vitality/static/js/bootstrap.bundle.js
  vitality/static/js/bootstrap.bundle.js.map
  vitality/static/js/bootstrap.bundle.min.js
  vitality/static/js/bootstrap.bundle.min.js.map
  vitality/static/js/bootstrap.js
  vitality/static/js/bootstrap.js.map
  vitality/static/js/bootstrap.min.js
  vitality/static/js/bootstrap.min.js.map
  vitality/static/js/jquery-3.5.1.min.js
  vitality/static/js/jquery-3.5.1.min.map
  vitality/templates/base.html
  vitality/templates/home.html
Labels: enhancement

#100 Formatted and laid out the foundation of the login and sign up pages.
  vitality/static/css/base.css
  vitality/templates/account/login.html
  vitality/templates/account/signup.html
Labels: enhancement

#102 Made nav bar bold.
  vitality/templates/base.html
Labels: enhancement

#79 Adding UsernameTakenError when a username in the database is found.
  vitality/__init__.py
  vitality/database.py
  vitality/templates/account/signup.html
Labels: bugfix, enhancement

#104 Adding disclaimer
  README.md
Labels: enhancement

#105 New Flask unittests
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/account/signup.html
Labels: enhancement

#107 Added a loading spinner while page loads.
  vitality/templates/base.html
Labels: enhancement

#109 If trainer tried to load trainee pages, or vice versa, then we 403.
  vitality/__init__.py
Labels: enhancement

#110 Added proper error pages.
  vitality/__init__.py
  vitality/templates/error/403.html
  vitality/templates/error/404.html
  vitality/templates/error/410.html
  vitality/templates/error/500.html
Labels: enhancement

#111 Adding -v tag to pytest
  .github/workflows/Unittests-and-Dependencies.yml
Labels: enhancement

#112 Added tests for flask app
  requirements.txt
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/error/400.html
Labels: enhancement

#113 Removed headers that were not needed.
  vitality/templates/trainee/list_trainers.html
  vitality/templates/trainee/schedule.html
  vitality/templates/trainer/list_trainees.html
  vitality/templates/trainer/schedule.html
Labels: enhancement

#116 Added Trainer Functions and added Trainee class
  tests/test_database.py
  tests/test_flask.py
  tests/test_user.py
  vitality/__init__.py
  vitality/database.py
  vitality/trainee.py
  vitality/trainer.py
  vitality/user.py
Labels: enhancement

#119 Renaming workout overview page
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/workout/workout.html
  vitality/templates/workout/workout_overview.html
Labels: enhancement

#120 Adding workout template
  vitality/templates/workout/workout.html
Labels: enhancement

#121 Changed workout templates to use basic bootstrap.
  vitality/templates/workout/new_workout.html
  vitality/templates/workout/search.html
  vitality/templates/workout/workout_overview.html
  vitality/templates/workout/workoutlist.html
Labels: enhancement

#122 Optimizations with database class
  vitality/database.py
Labels: enhancement

#123 Improved unit tests.
  helper/schema_atlas.py
  helper/schema_local.py
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/user.py
  vitality/workout.py
Labels: enhancement

#126 User can now sign up and login as both a Trainee or Trainer.
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/account/signup.html
  vitality/templates/trainer/list_trainees.html
Labels: enhancement

#127 Fixed navbar
  .gitignore
Labels: bugfix

#128 Refactored code that was reused multiple times.
  vitality/__init__.py
  vitality/database.py
  vitality/templates/base.html
Labels: enhancement

#129 Formatting
  vitality/__init__.py
  vitality/database.py
Labels: enhancement

#130 test_flask more checks
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
Labels: enhancement

#131 Adding .gitattributes
  .gitattributes
Labels: documentation

#132 Adding more checks to test_flask
  tests/test_flask.py
Labels: enhancement

#133 Refactored remaining logins.
  tests/test_flask.py
Labels: enhancement
