Repository santosderek/Vitality, pull requests merged in 2020-11, with the labels that each got.

#134 Tests, hints, code simplicity
  tests/test_database.py
  tests/test_flask.py
  tests/test_trainer.py
  tests/test_user.py
  vitality/__init__.py
  vitality/configuration.py
  vitality/database.py
  vitality/templates/account/profile.html
  vitality/templates/account/signup.html
  vitality/templates/account/usersettings.html
  vitality/templates/trainee/add_trainer.html
  vitality/templates/trainee/list_trainers.html
  vitality/templates/trainee/overview.html
  vitality/trainee.py
  vitality/trainer.py
  vitality/user.py
  vitality/workout.py
Labels: enhancement

#135 Added Trainer search
  tests/test_flask.py
  vitality/__init__.py
  vitality/static/css/base.css
  vitality/static/css/sidebar.css
  vitality/templates/trainee/add_trainer.html
  vitality/templates/trainee/list_trainers.html
  vitality/templates/trainee/overview.html
  vitality/templates/trainee/schedule.html
  vitality/templates/trainer/list_trainees.html
  vitality/templates/trainer/overview.html
  vitality/templates/trainer/schedule.html
Labels: enhancement

#136 User class constructors now use __dict__
  tests/test_flask.py
  tests/test_trainer.py
  vitality/trainee.py
  vitality/trainer.py
  vitality/user.py
Labels: enhancement

#137 Fixing hamburger menu.
  vitality/static/css/base.css
  vitality/static/images/bars.svg
Labels: enhancement

#138 Replaced all .id to ._id and trainers list to Trainee
  tests/test_database.py
  tests/test_flask.py
  tests/test_trainer.py
  tests/test_user.py
  vitality/__init__.py
  vitality/database.py
  vitality/trainee.py
  vitality/trainer.py
  vitality/user.py
  vitality/workout.py
Labels: enhancement

#139 Added navbar.html and sidebar.html with appropriate includes.
  vitality/templates/base.html
  vitality/templates/navbar.html
  vitality/templates/sidebar.html
  vitality/templates/trainee/add_trainer.html
  vitality/templates/trainee/list_trainers.html
  vitality/templates/trainee/overview.html
  vitality/templates/trainee/schedule.html
  vitality/templates/trainer/list_trainees.html
  vitality/templates/trainer/overview.html
  vitality/templates/trainer/schedule.html
Labels: enhancement

#140 Fomatting of base.html fixed.
  vitality/templates/base.html
Labels: enhancement

#141 Fixing profile page. Now checking trainers.
  vitality/__init__.py
Labels: enhancement

#143 Minor formatting of sidebar.html
  vitality/templates/sidebar.html
Labels: enhancement

#145 Updated the user class according to the UML.
  tests/test_trainee.py
  tests/test_trainer.py
  vitality/user.py
Labels: enhancement

#146 Removed the __dict__.update commands from user class.
  vitality/trainee.py
  vitality/trainer.py
  vitality/user.py
Labels: enhancement

#147 Laruffaelijah dev
  requirements.txt
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
Labels: enhancement

#148 Making add_trainee/trainer insert the class dictionary so it is dependent on the class definition.
  tests/test_database.py
  tests/test_trainer.py
  vitality/__init__.py
  vitality/database.py
  vitality/user.py
Labels: enhancement

#152 Trainee can now add trainer.
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/templates/trainee/list_trainers.html
  vitality/templates/trainee/overview.html
  vitality/templates/trainee/trainer_search.html
  vitality/trainee.py
  vitality/trainer.py
Labels: enhancement

#154 Trainers can now add trainees by search
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/templates/trainer/overview.html
  vitality/templates/trainer/trainee_search.html
Labels: enhancement

#155 user settings features
  vitality/__init__.py
  vitality/templates/account/delete.html
  vitality/templates/account/usersettings.html
  vitality/templates/navbar.html
Labels: enhancement

#156 Removing user_id from session, and adding an abort when no user found to delete.
  vitality/__init__.py
Labels: bugfix

#163 Trainer can now see all trainees that have added them. Also merged overview and list pages.
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/static/css/base.css
  vitality/static/css/login.css
  vitality/static/css/sidebar.css
  vitality/templates/base.html
  vitality/templates/home.html
  vitality/templates/sidebar.html
  vitality/templates/trainee/list_trainers.html
  vitality/templates/trainee/overview.html
  vitality/templates/trainee/trainer_search.html
  vitality/templates/trainer/list_trainees.html
  vitality/templates/trainer/overview.html
  vitality/templates/trainer/trainee_search.html
  vitality/templates/user/list_added.html
  vitality/templates/user/overview.html
  vitality/templates/user/schedule.html
Labels: enhancement

#164 Fixed bug where wrong links were given to the opposite class
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/sidebar.html
  vitality/templates/user/overview.html
Labels: bugfix

#165 Fixed formatting issues with buttons.
  vitality/static/css/base.css
  vitality/templates/account/usersettings.html
  vitality/templates/home.html
Labels: bugfix

#168 Added input validation for /usersettings and three new unit tests.
  tests/test_flask.py
  vitality/__init__.py
Labels: enhancement

#176 New workout functionality
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/static/images/dumbbell.svg
  vitality/templates/user/overview.html
  vitality/templates/workout/new_workout.html
  vitality/workout.py
Labels: enhancement

#179 166 Added try/exception, updated unit tests, added alert to webpages for invalid inputs.
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/account/login.html
  vitality/templates/account/signup.html
  vitality/templates/account/usersettings.html
Labels: bug, enhancement

#177 A removed trainee / trainer gets wiped from other's list
  tests/test_database.py
  vitality/database.py
Labels: bugfix

#174 Added dockerfile to use with docker-compose
  Dockerfile
Labels: enhancement

#180 Update README.md with Launch Instructions
  README.md
Labels: documentation

#181 Update README.md
  README.md
Labels: documentation

#182 Numbering and sudo
  README.md
Labels: documentation
