Repository santosderek/Vitality, pull requests merged in 2020-12, with the labels that each got.

#185 Docker build GH action
  .github/workflows/Unittests-and-Dependencies.yml
Labels: enhancement

#175 Workout Overview Functionality
  tests/test_flask.py
  vitality/__init__.py
  vitality/static/css/base.css
  vitality/templates/navbar.html
  vitality/templates/sidebar.html
  vitality/templates/user/overview.html
  vitality/templates/workout/workout_overview.html
Labels: enhancement

#186 Removed .container class
  vitality/static/css/base.css
  vitality/templates/base.html
Labels: enhancement

#183 Parkerbryson dev - delete unit tests
  tests/test_flask.py
  vitality/__init__.py
Labels: enhancement

#188 Invitation System and Remove User From List
  .coveragerc
  tests/test_database.py
  tests/test_flask.py
  tests/test_invitation.py
  tests/test_trainee.py
  vitality/__init__.py
  vitality/database.py
  vitality/invitation.py
  vitality/static/css/base.css
  vitality/templates/account/delete.html
  vitality/templates/trainer/trainee_search.html
  vitality/templates/user/list_added.html
  vitality/templates/user/list_invitations.html
  vitality/templates/user/overview.html
  vitality/trainee.py
  vitality/trainer.py
  vitality/user.py
Labels: enhancement

#194 Display the contents of a single workout
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/workout/workout.html
Labels: enhancement

#193 Create events.py
  vitality/events.py
Labels: enhancement

#199 Usernames are now lowercase and uppercase tests added
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
Labels: bug

#200 Added JavaScript to force user to use lowercase with usernames.
  vitality/__init__.py
  vitality/templates/account/login.html
  vitality/templates/account/signup.html
  vitality/templates/account/usersettings.html
Labels: enhancement

#202 Create test_event.py
  tests/test_event.py
Labels: enhancement

#201 Added dotenv and removed flask-pymongo
  .env.example
  .gitignore
  README.md
  configuration.json
  requirements.txt
  start_flask.bat
  start_flask.sh
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/configuration.py
  vitality/database.py
  vitality/settings.py
Labels: enhancement

#198 Added more tests and repr functions.
  tests/test_trainee.py
  tests/test_trainer.py
  tests/test_user.py
  tests/test_workout.py
  vitality/trainer.py
  vitality/workout.py
Labels: enhancement

#203 Show user created workouts in a list and have button link to workout
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/templates/workout/workoutlist.html
Labels: enhancement

#204 Fixed bug where the wrong button gets greyed out when inviting a user as a friend.
  vitality/templates/trainee/trainer_search.html
  vitality/templates/trainer/trainee_search.html
Labels: bugfix

#207 Continuous Deployment
  .github/workflows/Unittests-and-Dependencies.yml
  ansible/UpdateVitality.yml
Labels: enhancement

#210 Recommended changes for /workout
  helper/default_workouts.py
  tests/test_database.py
  tests/test_flask.py
  tests/test_trainee.py
  tests/test_trainer.py
  tests/test_user.py
  tests/test_workout.py
  vitality/__init__.py
  vitality/database.py
  vitality/static/css/base.css
  vitality/templates/account/profile.html
  vitality/templates/user/list_added.html
  vitality/templates/workout/new_workout.html
  vitality/templates/workout/search.html
  vitality/templates/workout/workout.html
  vitality/user.py
  vitality/workout.py
Labels: enhancement

#209 Gain experience points by workout
  helper/default_workouts.py
  tests/test_database.py
  tests/test_flask.py
  tests/test_trainee.py
  tests/test_trainer.py
  tests/test_user.py
  tests/test_workout.py
  vitality/__init__.py
  vitality/database.py
  vitality/static/css/base.css
  vitality/templates/account/profile.html
  vitality/templates/user/list_added.html
  vitality/templates/workout/new_workout.html
  vitality/templates/workout/search.html
  vitality/templates/workout/workout.html
  vitality/user.py
  vitality/workout.py
Labels: enhancement

#214 Fixes for location
  vitality/database.py
  vitality/user.py
Labels: bugfix

#213 Fixed issues found from meeting
  vitality/templates/workout/workout.html
Labels: enhancement

#215 Added conversion from user class to mongodb.
  vitality/database.py
Labels: enhancement

#212 Features Page
  tests/test_flask.py
  vitality/__init__.py
  vitality/templates/features.html
  vitality/templates/home.html
  vitality/templates/navbar.html
Labels: enhancement

#217 Not provided
  vitality/templates/workout/workout.html
Labels: enhancement

#216 Track time, miles, max reps, and categorize workouts
  tests/test_database.py
  tests/test_flask.py
  tests/test_workout.py
  vitality/__init__.py
  vitality/database.py
  vitality/templates/workout/new_workout.html
  vitality/templates/workout/workout.html
  vitality/workout.py
Labels: enhancement

#218 No errors
  vitality/__init__.py
  vitality/database.py
  vitality/templates/user/find_trainer_map.html
Labels: enhancement

#219 Santosderek map fix
  vitality/database.py
  vitality/templates/user/find_trainer_map.html
Labels: enhancement

#220 fix
  tests/test_database.py
  tests/test_flask.py
  tests/test_user.py
  vitality/templates/trainee/nearby_trainers.html
  vitality/templates/user/find_trainer_map.html
Labels: enhancement

#221 Event / Scheduling System
  tests/test_database.py
  tests/test_event.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/event.py
  vitality/events.py
  vitality/static/css/base.css
  vitality/templates/sidebar.html
  vitality/templates/trainee/schedule.html
  vitality/templates/user/add_event.html
  vitality/templates/user/event.html
  vitality/templates/user/overview.html
  vitality/templates/user/schedule.html
Labels: enhancement

#222 Parkerbryson map of trainers
  tests/test_database.py
  tests/test_flask.py
  tests/test_trainee.py
  tests/test_trainer.py
  tests/test_user.py
  vitality/__init__.py
  vitality/database.py
  vitality/templates/account/signup.html
  vitality/templates/account/usersettings.html
  vitality/templates/navbar.html
  vitality/templates/trainee/nearby_trainers.html
  vitality/templates/user/find_trainer_map.html
  vitality/templates/user/map.html
  vitality/trainee.py
  vitality/trainer.py
  vitality/user.py
Labels: enhancement

#223 Added the map to the profile page.
  .env.example
  README.md
  vitality/__init__.py
  vitality/settings.py
  vitality/static/css/base.css
  vitality/templates/account/profile.html
  vitality/templates/user/find_trainer_map.html
Labels: enhancement

#225 Fixes Not Provided Bug
  vitality/templates/workout/workout.html
Labels: bug

#226 Search for a workout
  tests/test_database.py
  tests/test_flask.py
  vitality/__init__.py
  vitality/database.py
  vitality/templates/workout/search.html
Labels: enhancement

#227 Map.html was still using a visible API key
  vitality/templates/user/map.html
Labels: bugfix

#228 Youtube Functionality
  .env.example
  .github/workflows/Unittests-and-Dependencies.yml
  requirements.txt
  tests/test_flask.py
  tests/test_youtube.py
  vitality/__init__.py
  vitality/settings.py
  vitality/static/images/hamburger.svg
  vitality/templates/diet/diets.html
  vitality/templates/diet/placeholder.html
  vitality/templates/diet/videos.html
  vitality/templates/sidebar.html
  vitality/templates/workout/search.html
  vitality/youtube.py
Labels: enhancement

#229 Re-added place-icon img tag.
  requirements.txt
  tests/test_flask.py
  tests/test_youtube.py
  vitality/templates/user/map.html
  vitality/youtube.py
Labels: bugfix

#230 Hotfix - 2020.12.19.12.40
  vitality/__init__.py
  vitality/templates/account/usersettings.html
  vitality/templates/diet/videos.html
  vitality/templates/workout/search.html
Labels: enhancement

#231 Hotfix 2020.12.19.10.12
  requirements.txt
  tests/test_youtube.py
  vitality/__init__.py
  vitality/youtube.py
Labels: enhancement
